export const agentApiAbi = [
    {
        "inputs":[
        ],
        "name":"InvalidInitialization",
        "type":"error"
    },
    {
        "inputs":[
        ],
        "name":"NotInitializing",
        "type":"error"
    },
    {
        "anonymous":false,
        "inputs":[
            {
                "indexed":false,
                "internalType":"uint64",
                "name":"version",
                "type":"uint64"
            }
        ],
        "name":"Initialized",
        "type":"event"
    },
    {
        "inputs":[
        ],
        "name":"agentId",
        "outputs":[
            {
                "internalType":"uint256",
                "name":"",
                "type":"uint256"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
        ],
        "name":"aileyApiContract",
        "outputs":[
            {
                "internalType":"contract AileyApi",
                "name":"",
                "type":"address"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
        ],
        "name":"aleToken",
        "outputs":[
            {
                "internalType":"contract Ailey",
                "name":"",
                "type":"address"
            }
        ],
        "stateMutability":"view",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"address",
                "name":"tokenA",
                "type":"address"
            },
            {
                "internalType":"address",
                "name":"tokenB",
                "type":"address"
            },
            {
                "internalType":"uint24",
                "name":"fee",
                "type":"uint24"
            },
            {
                "internalType":"int24",
                "name":"tickLower",
                "type":"int24"
            },
            {
                "internalType":"int24",
                "name":"tickUpper",
                "type":"int24"
            },
            {
                "internalType":"uint256",
                "name":"amountADesired",
                "type":"uint256"
            },
            {
                "internalType":"uint256",
                "name":"amountBDesired",
                "type":"uint256"
            },
            {
                "internalType":"uint256",
                "name":"amountAMin",
                "type":"uint256"
            },
            {
                "internalType":"uint256",
                "name":"amountBMin",
                "type":"uint256"
            },
            {
                "internalType":"address",
                "name":"to",
                "type":"address"
            },
            {
                "internalType":"uint256",
                "name":"deadline",
                "type":"uint256"
            }
        ],
        "name":"callAddLiquidity",
        "outputs":[
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"address",
                "name":"tokenIn",
                "type":"address"
            },
            {
                "internalType":"address",
                "name":"tokenOut",
                "type":"address"
            },
            {
                "internalType":"uint24",
                "name":"fee",
                "type":"uint24"
            },
            {
                "internalType":"uint256",
                "name":"amountIn",
                "type":"uint256"
            },
            {
                "internalType":"uint256",
                "name":"amountOutMinimum",
                "type":"uint256"
            },
            {
                "internalType":"address",
                "name":"recipient",
                "type":"address"
            },
            {
                "internalType":"uint256",
                "name":"deadline",
                "type":"uint256"
            }
        ],
        "name":"callSwap",
        "outputs":[
            {
                "internalType":"uint256",
                "name":"amountOut",
                "type":"uint256"
            }
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "inputs":[
        ],
        "name":"callTest",
        "outputs":[
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "inputs":[
            {
                "internalType":"uint256",
                "name":"_agentId",
                "type":"uint256"
            },
            {
                "internalType":"contract Ailey",
                "name":"_aleToken",
                "type":"address"
            },
            {
                "internalType":"contract AileyApi",
                "name":"_aileyApiContract",
                "type":"address"
            }
        ],
        "name":"initialize",
        "outputs":[
        ],
        "stateMutability":"nonpayable",
        "type":"function"
    },
    {
        "inputs":[
        ],
        "name":"version",
        "outputs":[
            {
                "internalType":"string",
                "name":"",
                "type":"string"
            }
        ],
        "stateMutability":"pure",
        "type":"function"
    }
]